### ISSUE TITLE
Session store and socket.io

### ISSUE THREAD

**Issue by kersten** [donpark/session-mongoose#1]
Hi,

I've tried to implement the session into socket.io and run into following error:

``` javascript
/home/kersten/Entwicklung/vdr-guia/node_modules/express/node_modules/connect/lib/middleware/session/session.js:83
  this.req.sessionStore.set(this.id, this, fn || function(){});
                        ^
TypeError: Cannot call method 'set' of undefined
    at Session.save (/home/kersten/Entwicklung/vdr-guia/node_modules/express/node_modules/connect/lib/middleware/session/session.js:83:25)
    at /home/kersten/Entwicklung/vdr-guia/src/controllers/AuthenticationController.js:16:36
    at [object Object].<anonymous> (/home/kersten/Entwicklung/vdr-guia/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection.js:505:7)
    at [object Object].emit (events.js:67:17)
    at [object Object].<anonymous> (/home/kersten/Entwicklung/vdr-guia/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connections/server.js:98:12)
    at [object Object].emit (events.js:64:17)
    at Socket.<anonymous> (/home/kersten/Entwicklung/vdr-guia/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection.js:102:16)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:676:14)
    at IOWatcher.onReadable [as callback] (net.js:177:10)
```

This is the code that throws the error:

``` javascript
UserModel.count({user: data.username, password: data.password}, function (err, count) {
            var loggedIn = false;

            if (count != 0) {
                console.log(hs.sessionID);
                mongooseSessionStore.set(hs.sessionID, {loggedIn: true});
                loggedIn = true;
                hs.session.loggedIn = true;

                hs.session.touch().save();
            }

            socket.emit('User:login', {loggedIn: loggedIn});
        });
```

The line is hs.session.touch().save(); that throws it.

Could you have a look at it?

**Comment by donpark** [comment]
Error thrown suggests `hs.session.req.sessionStore` field is `undefined`.

Have you tried replacing `session-mongoose` with another SessionStore implementation?

**Comment by kersten** [comment]
Yes tried this with redis and that worked.

**Comment by kersten** [comment]
I'am in the train right now. Could send you the Code when i am at home

**Comment by kersten** [comment]
Hi, you can find the store I've used here: https://github.com/visionmedia/connect-redis

**Comment by kersten** [comment]
I try to fix it by myself and will give your the patch

**Comment by kersten** [comment]
Ok, sorry was a bug in my code. Works allready. Sorry for the trouble!

**Comment by donpark** [comment]
np. I do the same occasionally. :-)

**Comment by robert-cardillo** [comment]
Same happened to me but I solved it too. This line was missing in socket.io authorization:

``` javascript
data.sessionStore = sessionStore;
```
