### ISSUE TITLE
Crash since last update

### ISSUE THREAD

**Issue by mathieug** [donpark/session-mongoose#5]
```
events.js:66
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: Trying to open unclosed connection.
    at NativeConnection.Connection.open ([...]/node_modules/mongoose/lib/connection.js:191:15)
    at Mongoose.connect ([...]/node_modules/mongoose/lib/index.js:131:15)
    at new SessionStore ([...]/node_modules/session-mongoose/index.js:49:16)
    at Function.<anonymous> ([...]/app.js:18:15)
    at Function.app.configure ([...]/node_modules/express/lib/application.js:399:61)
    at Object.<anonymous> ([...]/app.js:13:5)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

package.json dependencies

``````
  "dependencies": {
    "express": "latest",
    "mongoose": "3.0.3",
    "session-mongoose": "0.0.4"
  }```
``````

**Comment by donpark** [comment]
could you try version 0.0.5? I think I didn't replicate `mongeese` exactly in 0.0.4.

**Comment by mathieug** [comment]
Could you update on npmjs?

**Comment by donpark** [comment]
it should be updated already.

**Comment by mathieug** [comment]
Look at https://npmjs.org/package/session-mongoose

**Comment by donpark** [comment]
Found some bewildering behaviors which I've no time to chase at the moment so I've unpublished version 0.0.4 and 0.0.5.

Please use version 0.0.3 until I can figure it out. Changes didn't add any new functions anyway.

**Comment by donpark** [comment]
Both `mongeese` and `session-mongoose` masters are back to equivalent to original code but will not be published until further testing can be done.
